server:
  port: 8087

spring:
  datasource:
    name: library
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: Buggu@12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
